library(pareto)
set.seed(11)

# If `length(n) == 1`, the function generates `n` values from the distribution.  
rpareto(10, 1, 1)

# If `length(n) > 1`, the function generates `length(n)` values from the distribution.  
rpareto(1:5, 1, 2)

# If out-of-range arguments are inputed, the function returns NaNs.  
rpareto(5, 1, -1)


# `rpareto` approximates the quantiles generated by `qpareto`:  
set.seed(122)
val.r <- rpareto(1000, 2, 2)
val.q <- qpareto(seq(0,1,0.001), 2, 2)
plot(density(val.r), main = "", xlab = "x", ylab = "Density", xlim = c(0, 50), ylim = c(0, 0.6))
par(new=TRUE)
plot(density(val.q), col = "red", lty = 2, main = "", xlab = "x", ylab = "Density", xlim = c(0, 50), ylim = c(0, 0.6))